version: '2'
services:
  cassandra:
    image: cassandra:5.0-beta1
    ports:
      - 9042:9042
    ulimits:
      memlock: -1

 
# If you want to have cqlsh
#  docker exec -it `docker ps | grep assandra:5.0-beta1 | cut -b 1-12` cqlsh

    
  